apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  # Use rbac-namespace.yaml for namespace-scoped deployment (Recommended)
  # Or use rbac-cluster.yaml if cluster-wide Secrets access is required
  - rbac-namespace.yaml
  #- rbac-cluster.yaml
  - configmap.yaml
  - service.yaml
