apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mikrotik-cert-controller

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: mikrotik-cert-controller
    behavior: create
    files:
      - config.yaml
      - known_hosts
    options:
      disableNameSuffixHash: true
